version: 2

workflows:
  version: 2
  release:
    jobs:
    - release:
        filters:
          branches:
            only: production

jobs:
  release:
    machine: true
    environment:
      PACKAGE: gyazo
      VERSION: 1.3.1
    steps:
      - checkout
      - run: gem install package_cloud
      - run:
          command: |
            sh ./deb.sh
            ruby ./circle_release.rb
            bash ./rpm_docker.sh
